# Generated by Django 3.0.1 on 2019-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191223_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proyecto',
            field=models.ManyToManyField(blank=True, to='mainApp.Proyecto'),
        ),
    ]
