# Generated by Django 3.0.1 on 2019-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20191223_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promedio_puntuaciones',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
