# Generated by Django 3.0.1 on 2019-12-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191226_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='proyecto',
            new_name='proyectos',
        ),
    ]
